spring.application.name=taxsystem

spring.datasource.url=jdbc:postgresql://localhost:5432/taxsystem
spring.datasource.username=postgres
spring.datasource.password=ibra@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

server.port=8080